@extends('layouts.app')

@section('content')
<div class="space-y-6">
    <header class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wider text-[#9f2f25]">Control de gestión</p><h1 class="text-3xl font-black text-gray-900">{{ $panel === 'auditoria' ? 'Reporte de auditoría' : 'Reporte de ventas' }}</h1><p class="mt-1 text-sm text-gray-500">{{ $panel === 'auditoria' ? 'Cambios importantes registrados en el sistema.' : 'Ventas recientes, facturas y trazabilidad comercial.' }}</p></div>@if($panel === 'ventas')<div class="flex gap-2"><a href="{{ route('reportes.exportar', request()->query() + ['formato' => 'csv']) }}" class="rounded-md border border-[#b52f25] px-4 py-2 font-bold text-[#9f2f25]">Reporte de ventas Excel</a><a href="{{ route('reportes.exportar', request()->query() + ['formato' => 'pdf']) }}" class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white">Reporte de ventas PDF</a></div>@else<span class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white">Reporte de auditoría</span>@endif</header>
    <nav class="flex gap-2 border-b border-[#e8c8c3]"><a href="{{ route('reportes.index', request()->except(['panel', 'audit_accion', 'audit_modelo', 'audit_usuario', 'audit_registro', 'audit_desde', 'audit_hasta'])) }}" class="border-b-2 px-4 py-3 text-sm font-bold {{ $panel === 'ventas' ? 'border-[#b52f25] text-[#9f2f25]' : 'border-transparent text-gray-500' }}">Reportes de ventas</a><a href="{{ route('reportes.index', request()->query() + ['panel' => 'auditoria']) }}" class="border-b-2 px-4 py-3 text-sm font-bold {{ $panel === 'auditoria' ? 'border-[#b52f25] text-[#9f2f25]' : 'border-transparent text-gray-500' }}">Reportes de auditoría</a></nav>

    @if($panel === 'auditoria')
        <form method="GET" class="grid gap-3 rounded-lg bg-white p-5 shadow-sm md:grid-cols-3 lg:grid-cols-6"><input type="hidden" name="panel" value="auditoria"><select name="audit_accion" class="rounded-md border p-2"><option value="">Todas las acciones</option>@foreach($acciones as $accion)<option value="{{ $accion }}" @selected(request('audit_accion') === $accion)>{{ ucfirst($accion) }}</option>@endforeach</select><select name="audit_modelo" class="rounded-md border p-2"><option value="">Todos los módulos</option>@foreach($modelos as $modelo)<option value="{{ $modelo }}" @selected(request('audit_modelo') === $modelo)>{{ class_basename($modelo) }}</option>@endforeach</select><select name="audit_usuario" class="rounded-md border p-2"><option value="">Todos los usuarios</option>@foreach($usuarios as $usuario)<option value="{{ $usuario->id }}" @selected((string) request('audit_usuario') === (string) $usuario->id)>{{ $usuario->name }}</option>@endforeach</select><input type="number" name="audit_registro" value="{{ request('audit_registro') }}" placeholder="ID de registro" class="rounded-md border p-2"><input type="date" name="audit_desde" value="{{ request('audit_desde') }}" class="rounded-md border p-2"><input type="date" name="audit_hasta" value="{{ request('audit_hasta') }}" class="rounded-md border p-2"><button class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white lg:col-start-6">Filtrar</button></form>
        <section class="overflow-x-auto rounded-lg bg-white shadow-sm"><div class="border-b border-gray-100 p-5"><h2 class="text-lg font-black">Cambios registrados</h2><p class="mt-1 text-sm text-gray-500">Las operaciones masivas se muestran como una sola importación.</p></div><table class="min-w-full text-left text-sm"><thead class="bg-[#f7e8e6] text-xs uppercase text-[#8f241d]"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Usuario</th><th class="px-5 py-3">Cambio</th><th class="px-5 py-3">Módulo</th><th class="px-5 py-3">Detalle</th></tr></thead><tbody class="divide-y">@forelse($auditorias as $auditoria)<tr><td class="whitespace-nowrap px-5 py-3">{{ $auditoria->created_at->format('d/m/Y H:i') }}</td><td class="px-5 py-3">{{ $auditoria->usuario?->name ?? 'Sistema' }}</td><td class="px-5 py-3 font-bold text-[#9f2f25]">{{ $auditoria->es_importacion ? 'Importación de datos' : ucfirst($auditoria->accion) }}</td><td class="px-5 py-3">{{ $auditoria->es_importacion ? 'Base de datos' : class_basename($auditoria->modelo) }}</td><td class="px-5 py-3"><details><summary class="cursor-pointer font-bold text-[#9f2f25]">{{ $auditoria->es_importacion ? 'Se importaron '.$auditoria->cantidad_agrupada.' registros' : 'Ver detalle' }}</summary>@unless($auditoria->es_importacion)<div class="mt-2 space-y-1 text-xs"><p><strong>Registro:</strong> #{{ $auditoria->modelo_id ?? 'N/A' }}</p><p><strong>Resultado:</strong> {{ $auditoria->datos_nuevos ? 'Se guardó la nueva información.' : 'Se eliminó la información.' }}</p><p><strong>IP:</strong> {{ $auditoria->ip ?? 'No disponible' }}</p></div>@endunless</details></td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-gray-500">No hay cambios para los filtros seleccionados.</td></tr>@endforelse</tbody></table><div class="p-5">{{ $auditorias->appends(request()->query())->links() }}</div></section>
    @else
        <form method="GET" class="grid gap-3 rounded-lg bg-white p-5 shadow-sm md:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="panel" value="ventas"><input type="date" name="desde" value="{{ $desde->toDateString() }}" class="rounded-md border p-2" aria-label="Desde"><input type="date" name="hasta" value="{{ $hasta->toDateString() }}" class="rounded-md border p-2" aria-label="Hasta"><input type="number" name="venta_id" value="{{ request('venta_id') }}" placeholder="N° de venta" class="rounded-md border p-2"><input type="search" name="cliente" value="{{ request('cliente') }}" placeholder="Cliente o RUT" class="rounded-md border p-2"><select name="usuario" class="rounded-md border p-2"><option value="">Todos los vendedores</option>@foreach($usuarios as $usuario)<option value="{{ $usuario->id }}" @selected((string) request('usuario') === (string) $usuario->id)>{{ $usuario->name }}</option>@endforeach</select><select name="medio_pago" class="rounded-md border p-2"><option value="">Todos los medios de pago</option>@foreach(['Efectivo','Transferencia','Tarjeta','Otro'] as $medio)<option value="{{ $medio }}" @selected(request('medio_pago') === $medio)>{{ $medio }}</option>@endforeach</select><button class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white lg:col-start-5">Aplicar filtros</button></form>
        <div class="grid grid-cols-1 gap-4 md:grid-cols-3"><div class="rounded-lg bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Ventas totales</p><p class="mt-2 text-3xl font-black text-[#9f2f25]">{{ $resumen->cantidad }}</p></div><div class="rounded-lg bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Total vendido</p><p class="mt-2 text-3xl font-black text-[#9f2f25]">$ {{ number_format($resumen->total, 0, ',', '.') }}</p></div><div class="rounded-lg bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Solicitudes pendientes</p><p class="mt-2 text-3xl font-black text-[#9f2f25]">{{ $pendientes }}</p></div></div>
        <section class="overflow-x-auto rounded-lg bg-white shadow-sm"><div class="border-b border-gray-100 p-5"><h2 class="text-lg font-black">Últimas ventas</h2><p class="mt-1 text-sm text-gray-500">Filtra y gestiona reportes o facturas individuales.</p></div><table class="min-w-full text-left text-sm"><thead class="bg-[#f7e8e6] text-xs uppercase text-[#8f241d]"><tr><th class="px-5 py-3">Venta</th><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Cliente</th><th class="px-5 py-3">Vendedor</th><th class="px-5 py-3">Pago</th><th class="px-5 py-3">Total</th><th class="px-5 py-3">Acciones</th></tr></thead><tbody class="divide-y">@forelse($ventas as $venta)<tr><td class="px-5 py-3 font-bold">#{{ $venta->id_venta }}</td><td class="whitespace-nowrap px-5 py-3">{{ $venta->fecha->format('d/m/Y H:i') }}</td><td class="px-5 py-3">{{ $venta->cliente?->nombre ?? 'Sin cliente' }}</td><td class="px-5 py-3">{{ $venta->user?->name ?? 'Sin usuario' }}</td><td class="px-5 py-3">{{ $venta->medio_pago }}</td><td class="px-5 py-3 font-bold">$ {{ number_format($venta->total, 0, ',', '.') }}</td><td class="px-5 py-3"><button type="button" data-sale-detail="{{ route('reportes.ventas.detalle', $venta->id_venta) }}" data-sale-invoice="{{ route('reportes.ventas.factura', $venta->id_venta) }}" class="rounded-md bg-[#b52f25] px-3 py-2 text-xs font-bold text-white">Ver factura</button></td></tr>@empty<tr><td colspan="7" class="px-5 py-8 text-center text-gray-500">No hay ventas para los filtros seleccionados.</td></tr>@endforelse</tbody></table><div class="p-5">{{ $ventas->appends(request()->query())->links() }}</div></section>
    @endif
</div>

<div id="sale-modal" class="fixed inset-0 z-50 hidden overflow-y-auto bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="sale-modal-title"><div class="mx-auto mt-8 max-w-3xl rounded-lg bg-white shadow-2xl"><div class="flex items-center justify-between border-b p-5"><div><p class="text-xs font-bold uppercase tracking-wider text-[#9f2f25]">Factura de venta</p><h2 id="sale-modal-title" class="text-xl font-black">Detalle</h2></div><button type="button" id="close-sale-modal" class="rounded-md px-3 py-2 text-2xl text-gray-500" aria-label="Cerrar">&times;</button></div><div id="sale-modal-content" class="p-5"><p class="text-gray-500">Cargando detalle...</p></div><div class="flex justify-end gap-2 border-t bg-gray-50 p-5"><a id="sale-invoice-link" href="#" class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white">Descargar factura PDF</a><button type="button" id="cancel-sale-modal" class="rounded-md border px-4 py-2 font-bold">Cerrar</button></div></div></div>
<script>
const saleModal = document.getElementById('sale-modal');
const saleContent = document.getElementById('sale-modal-content');
const invoiceLink = document.getElementById('sale-invoice-link');
const money = value => '$ ' + new Intl.NumberFormat('es-CL', { maximumFractionDigits: 0 }).format(value);
const closeSaleModal = () => saleModal?.classList.add('hidden');
document.querySelectorAll('[data-sale-detail]').forEach(button => button.addEventListener('click', async () => {
    saleModal.classList.remove('hidden');
    saleContent.innerHTML = '<p class="text-gray-500">Cargando detalle...</p>';
    invoiceLink.href = button.dataset.saleInvoice;
    try {
        const sale = await fetch(button.dataset.saleDetail, { headers: { Accept: 'application/json' } }).then(response => response.json());
        saleContent.innerHTML = `<div class="grid gap-4 text-sm md:grid-cols-3"><div><span class="text-gray-500">Venta</span><strong class="block">#${sale.id_venta}</strong></div><div><span class="text-gray-500">Fecha</span><strong class="block">${sale.fecha}</strong></div><div><span class="text-gray-500">Cliente</span><strong class="block">${sale.cliente}</strong></div><div><span class="text-gray-500">Vendedor</span><strong class="block">${sale.usuario}</strong></div><div><span class="text-gray-500">Pago</span><strong class="block">${sale.medio_pago}</strong></div></div><div class="mt-6 overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-[#f7e8e6] text-xs uppercase text-[#8f241d]"><tr><th class="px-3 py-2">Producto</th><th class="px-3 py-2">Cantidad</th><th class="px-3 py-2">Subtotal</th></tr></thead><tbody class="divide-y">${sale.detalles.map(item => `<tr><td class="px-3 py-2">${item.producto}</td><td class="px-3 py-2">${item.cantidad}</td><td class="px-3 py-2 font-bold">${money(item.subtotal)}</td></tr>`).join('')}</tbody></table></div><div class="mt-5 ml-auto max-w-xs space-y-2 text-right text-sm"><p>Neto: <strong>${money(sale.neto)}</strong></p><p>IVA: <strong>${money(sale.iva)}</strong></p><p class="border-t pt-2 text-lg">Total: <strong class="text-[#b52f25]">${money(sale.total)}</strong></p></div>`;
    } catch (error) {
        saleContent.innerHTML = '<p class="text-red-700">No fue posible cargar el detalle.</p>';
    }
}));
document.getElementById('close-sale-modal')?.addEventListener('click', closeSaleModal);
document.getElementById('cancel-sale-modal')?.addEventListener('click', closeSaleModal);
saleModal?.addEventListener('click', event => { if (event.target === saleModal) closeSaleModal(); });
</script>
<script>
    const auditButton = [...document.querySelectorAll('header span')].find(element => element.textContent.trim() === 'Reporte de auditoría');
    const auditSection = [...document.querySelectorAll('section')].find(element => element.textContent.includes('Cambios registrados'));
    const auditCsvUrl = @json(route('reportes.auditoria.exportar', request()->query() + ['formato' => 'csv']));
    const auditPdfUrl = @json(route('reportes.auditoria.exportar', request()->query() + ['formato' => 'pdf']));

    if (auditButton && auditSection) {
        auditButton.outerHTML = `<div class="flex gap-2"><a href="${auditCsvUrl}" class="rounded-md border border-[#b52f25] px-4 py-2 font-bold text-[#9f2f25]">Auditoría Excel</a><a href="${auditPdfUrl}" class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white">Auditoría PDF</a></div>`;
    }
</script>
@endsection
