@extends('layouts.app')
@section('content')
<div class="space-y-6">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wider text-[#9f2f25]">Control de gestión</p><h1 class="text-3xl font-black text-gray-900">Reportes</h1></div><div class="flex flex-wrap gap-2"><a href="{{ route('reportes.exportar', ['formato' => 'csv', 'desde' => $desde->toDateString(), 'hasta' => $hasta->toDateString()]) }}" class="rounded-md border border-[#b52f25] px-4 py-2 font-bold text-[#9f2f25] hover:bg-[#f7e8e6]">Excel</a><a href="{{ route('reportes.exportar', ['formato' => 'pdf', 'desde' => $desde->toDateString(), 'hasta' => $hasta->toDateString()]) }}" class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white hover:bg-[#8f241d]">PDF</a><a href="{{ route('reportes.auditoria') }}" class="rounded-md border border-[#b52f25] px-4 py-2 font-bold text-[#9f2f25] hover:bg-[#f7e8e6]">Auditoría</a></div></div>
    <form method="GET" class="flex flex-wrap items-end gap-3 rounded-lg bg-white p-4 shadow-md"><div><label class="block text-xs font-bold text-gray-600">Desde</label><input type="date" name="desde" value="{{ $desde->toDateString() }}" class="mt-1 rounded-md border p-2"></div><div><label class="block text-xs font-bold text-gray-600">Hasta</label><input type="date" name="hasta" value="{{ $hasta->toDateString() }}" class="mt-1 rounded-md border p-2"></div><button class="rounded-md bg-[#b52f25] px-4 py-2 font-bold text-white hover:bg-[#8f241d]">Actualizar</button></form>
    <div class="grid grid-cols-1 gap-4 md:grid-cols-3"><div class="rounded-lg bg-white p-5 shadow-md"><p class="text-sm text-gray-500">Ventas</p><p class="mt-2 text-3xl font-black text-[#9f2f25]">{{ $resumen->cantidad }}</p></div><div class="rounded-lg bg-white p-5 shadow-md"><p class="text-sm text-gray-500">Total vendido</p><p class="mt-2 text-3xl font-black text-[#9f2f25]">$ {{ number_format($resumen->total, 0, ',', '.') }}</p></div><div class="rounded-lg bg-white p-5 shadow-md"><p class="text-sm text-gray-500">IVA recaudado</p><p class="mt-2 text-3xl font-black text-[#9f2f25]">$ {{ number_format($resumen->iva, 0, ',', '.') }}</p></div></div>
    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2"><section class="rounded-lg bg-white p-5 shadow-md"><h2 class="text-lg font-black">Productos más vendidos</h2><div class="mt-4 divide-y">@forelse($masVendidos as $producto)<div class="flex justify-between py-3 text-sm"><span>{{ $producto->nombre }} <small class="text-gray-500">{{ $producto->codigo_barra }}</small></span><strong>{{ $producto->cantidad }}</strong></div>@empty<p class="py-4 text-sm text-gray-500">No hay ventas en el período.</p>@endforelse</div></section><section class="rounded-lg bg-white p-5 shadow-md"><h2 class="text-lg font-black">Stock crítico</h2><div class="mt-4 divide-y">@forelse($stockCritico as $producto)<div class="flex justify-between py-3 text-sm"><span>{{ $producto->nombre }}</span><strong class="text-red-700">{{ $producto->stock }}</strong></div>@empty<p class="py-4 text-sm text-gray-500">No hay productos en stock crítico.</p>@endforelse</div></section></div>
    <section class="overflow-x-auto rounded-lg bg-white shadow-md"><h2 class="p-5 text-lg font-black">Ventas del período</h2><table class="min-w-full text-left text-sm"><thead class="bg-[#f7e8e6] text-xs uppercase text-[#8f241d]"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Cliente</th><th class="px-5 py-3">Usuario</th><th class="px-5 py-3">Medio de pago</th><th class="px-5 py-3">Total</th></tr></thead><tbody class="divide-y">@forelse($ventas as $venta)<tr><td class="px-5 py-3">{{ $venta->fecha->format('d/m/Y H:i') }}</td><td class="px-5 py-3">{{ $venta->cliente?->nombre ?? 'Sin cliente' }}</td><td class="px-5 py-3">{{ $venta->user?->name ?? 'Sin usuario' }}</td><td class="px-5 py-3">{{ $venta->medio_pago }}</td><td class="px-5 py-3 font-bold">$ {{ number_format($venta->total, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-6 text-center text-gray-500">No hay ventas.</td></tr>@endforelse</tbody></table><div class="p-5">{{ $ventas->links() }}</div></section>
</div>
@endsection
