<!doctype html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Catálogo | RESMAP</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-[#f2efe8] text-[#17211f] antialiased">
<header class="border-b border-[#d9d4c8] bg-[#173d3a] text-white"><nav class="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-8"><a href="{{ route('home') }}" class="font-black tracking-[.2em]">RESMAP</a><a href="{{ route('home') }}" class="text-sm font-bold text-[#f6b941]">Volver al inicio</a></nav></header>
<main class="mx-auto max-w-7xl px-6 py-12 lg:px-8">
    <div class="max-w-2xl"><p class="text-sm font-bold uppercase tracking-[.25em] text-[#b06a22]">Catálogo de repuestos</p><h1 class="mt-2 text-5xl font-black tracking-tight">Encuentra lo que necesitas.</h1></div>
    @if(session('success'))<div class="mt-8 border-l-4 border-[#23635f] bg-white p-4 font-semibold">{{ session('success') }}</div>@endif
    <form method="GET" class="mt-10 grid gap-3 bg-white p-5 shadow-sm md:grid-cols-[1fr_240px_auto]"><input name="nombre" value="{{ request('nombre') }}" placeholder="Buscar por nombre" class="border border-gray-300 p-3"><select name="categoria" class="border border-gray-300 p-3"><option value="">Todas las categorías</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id_categoria }}" @selected(request('categoria') == $categoria->id_categoria)>{{ $categoria->nombre_categoria }}</option>@endforeach</select><button class="bg-[#23635f] px-6 py-3 font-bold text-white">Buscar</button></form>
    <div class="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        @foreach($productos as $producto)<article class="flex flex-col justify-between bg-white p-6 shadow-sm"><div><p class="text-xs font-bold uppercase tracking-wider text-[#b06a22]">{{ $producto->categoria->nombre_categoria ?? 'Repuesto' }}</p><h2 class="mt-3 text-lg font-black">{{ $producto->nombre }}</h2><p class="mt-2 text-sm text-gray-500">Código: {{ $producto->codigo_origen ?: 'Consultar' }}</p></div><div class="mt-7 flex items-end justify-between"><span class="text-xl font-black">$ {{ number_format($producto->precio, 0, ',', '.') }}</span><button type="button" onclick="agregar({{ $producto->id_producto }}, @js($producto->nombre))" class="rounded-full bg-[#f6b941] px-4 py-2 text-sm font-bold">Solicitar</button></div></article>@endforeach
    </div>
    <div class="mt-8">{{ $productos->links() }}</div>
    <section id="solicitud" class="mt-20 grid gap-10 bg-[#173d3a] p-8 text-white lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div><p class="text-sm font-bold uppercase tracking-[.25em] text-[#f6b941]">Tu pedido</p><h2 class="mt-3 text-3xl font-black">Envíanos tu solicitud.</h2><p class="mt-4 text-white/70">Selecciona productos, déjanos tus datos y te contactaremos para confirmar disponibilidad.</p><div id="seleccion" class="mt-6 space-y-2 text-sm"></div></div><form method="POST" action="{{ route('catalogo.solicitudes.store') }}" class="grid gap-4 sm:grid-cols-2">@csrf<div id="detalles_productos"></div><input name="rut" required placeholder="RUT" class="border-0 p-3 text-[#17211f]"><input name="nombre" required placeholder="Nombre o razón social" class="border-0 p-3 text-[#17211f]"><input name="correo" type="email" placeholder="Correo" class="border-0 p-3 text-[#17211f]"><input name="telefono" placeholder="Teléfono" class="border-0 p-3 text-[#17211f]"><input name="direccion" placeholder="Dirección" class="border-0 p-3 text-[#17211f] sm:col-span-2"><button class="bg-[#f6b941] p-3 font-bold text-[#17211f] sm:col-span-2">Enviar solicitud</button></form></section>
</main>
<script>const seleccion={};function agregar(id,nombre){seleccion[id]=(seleccion[id]||{id_producto:id,cantidad:0,nombre});seleccion[id].cantidad++;document.getElementById('seleccion').innerHTML=Object.values(seleccion).map(i=>`<div>${i.nombre} <strong>x${i.cantidad}</strong></div>`).join('');document.getElementById('detalles_productos').innerHTML=Object.values(seleccion).map((i,index)=>`<input type="hidden" name="detalles_productos[${index}][id_producto]" value="${i.id_producto}"><input type="hidden" name="detalles_productos[${index}][cantidad]" value="${i.cantidad}">`).join('');document.getElementById('solicitud').scrollIntoView({behavior:'smooth'});}</script>
</body></html>
